# Generated by Django 5.2.6 on 2025-09-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                (
                    "character_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("birthday", models.DateTimeField()),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USA", "Estados Unidos"),
                            ("BRAZIL", "Brasil"),
                            ("JAPAN", "Japão"),
                            ("UK", "Reino Unido"),
                            ("GERMANY", "Alemanha"),
                            ("BELGIUM", "Bélgica"),
                            ("FRANCE", "França"),
                            ("CANADA", "Cánada"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
