# Generated by Django 5.2.6 on 2025-09-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actors",
            name="birthday",
            field=models.DateField(),
        ),
    ]
