# Generated by Django 5.2.6 on 2025-09-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0002_alter_actors_birthday"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Actors",
            new_name="Actor",
        ),
    ]
