# Generated by Django 5.2.6 on 2025-09-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
    ]
