# Generated by Django 5.2.6 on 2025-09-14 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genres", "0001_initial"),
        ("movies", "0002_remove_movie_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movies",
                to="genres.genre",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
